name: The Craft
favicon: null
layout_spectrum: 0
typography_spectrum: 0.72254
title: Architectural Visualization Craftsmen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211e25'
    - '#06050a'
    - '#443a43'
    - '#84644e'
    - '#bd9677'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0
purpose: []
