typography_spectrum: 0.72254
color:
  brandColors:
    - '#211e25'
    - '#06050a'
    - '#443a43'
    - '#84644e'
    - '#bd9677'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.9375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: The Craft
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Architectural Visualization Craftsmen
description: Relax! We've got you covered ;)
purpose: []
