layout_spectrum: 0.25767329079099
typography_spectrum: 0.8610237196553499
color:
  brandColors:
    - '#0C0C0C'
    - '#363636'
    - '#FFFFFF'
    - '#878787'
    - '#D1D1D1'
  brandStrength: 0.31465314771048725
  lightness: 0.40323071694001555
  saturation: 0.30111548118293285
  rhythmicContrast: 0.9743119918275625
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e2dc14f-625a-43a3-a4ae-0e19401c4574.svg
name: The Craft
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact us!
    url: 'https://ronenbekerman.typeform.com/to/Zab166'
    type: external
favicon: null
title: Architectural Visualization Craftsmen
description: Relax! We've got you covered ;)
purpose: []
