name: The Craft
favicon: null
layout_spectrum: 0.05911134579218924
typography_spectrum: 0.40039823739789426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1740867483895272
  lightness: 0.7250364357605577
  saturation: 0.0033527836203575134
  rhythmicContrast: 0.2887377634178847
purpose: []
